# Generated by Django 5.2.3 on 2025-10-04 15:27

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_feedingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='date',
            field=models.DateField(default=students.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
